### ISSUE TITLE
Hacktoberfest Task : Core Features (Note Creation)

### ISSUE THREAD

**Issue by rizkytegar** [rizkytegar/veonote#37]
- [ ] Implement a feature to add new notes.
- [ ] Ensure that note data is stored in localStorage and remains intact after the page is refreshed.
- [ ] Add input validation (e.g., no note should have an empty title).

**Comment by kanikaa-3018** [comment]
> * [X]  Implement a feature to add new notes.
> * [X]  Ensure that note data is stored in localStorage and remains intact after the page is refreshed.
> * [X]  Add input validation (e.g., no note should have an empty title).

please assign me this task for hacktoberfest2024

**Comment by rhnas110** [comment]
Pagi bang, boleh assign issue ini ke gw ga? lagi coba-coba ikut hacktoberfest bang.
Untuk add note nya mau gimana ya bang? secara flow...

Kalo dari gw button + Add Note ketika di klik akan open modal, karena gw liat pake daisyui, bakal pake component modal dari daisy, untuk validation boleh ga gw pake zod dan react hook form buat handle formnya.

Untuk data note nya, base nya:
{
    id: number,
    title: string, // (kalo perlu set minimal length, maximal length berapa bang?)
    description: string, // (kalo perlu set minimal length, maximal length berapa bang?)
}

**Comment by rizkytegar** [comment]
@rhnas110 boleh bang, saya masih sibuk. buat 4 pull request aja nanti saya acc

**Comment by rhnas110** [comment]
oke bang, gw coba dari add/create note dulu

**Comment by rhnas110** [comment]
@rizkytegar udh gw PR bang yg add/create note
