### ISSUE TITLE
Hacktoberfest Task : Core Features (Delete Notes)

### ISSUE THREAD

**Issue by rizkytegar** [rizkytegar/veonote#40]
- [ ] Implement a feature to delete notes.
- [ ] After deletion, notes should no longer be displayed in the UI, and localStorage must be updated.

**Comment by pranjalee30** [comment]
@rizkytegar Hello Sir, Can you please assign this to me, I want to work on it.

**Comment by pranjalee30** [comment]
There are not any codebase only folder structure how can I get the data to be deleted. firstly I need the codebase of your veonotes. Could you please provide  more details

**Comment by rohitmore07** [comment]
Hey @rizkytegar I am very keen to work on this issue . I would be really happy if you could assign this issue to me.
