### ISSUE TITLE
Hacktoberfest Task : Design & Responsiveness Features

### ISSUE THREAD

**Issue by rizkytegar** [rizkytegar/veonote#43]
## Responsive Design
- [x] Ensure the UI is responsive for various screen sizes (mobile, tablet, desktop) using Tailwind CSS.

## Dark/Light Mode Toggle

- [x] Implement a dark and light mode feature.
- [ ] User preferences should be stored in localStorage so that user settings remain active after a reload.
UI/UX Enhancement

## Simple Animations for Actions

- [ ] Add small animations when users add, edit, or delete notes to enhance user experience.

**Comment by kanikaa-3018** [comment]
hey @rizkytegar , im willing to do this project for hacktoberfest2024, please assign me this. I can implement all the 4 assigned tasks with ease

**Comment by kanikaa-3018** [comment]
> ## Responsive Design
> * [X]  Ensure the UI is responsive for various screen sizes (mobile, tablet, desktop) using Tailwind CSS.
> 
> ## Dark/Light Mode Toggle
> * [X]  Implement a dark and light mode feature.
> * [X]  User preferences should be stored in localStorage so that user settings remain active after a reload.
>   UI/UX Enhancement
> 
> ## Simple Animations for Actions
> * [X]  Add small animations when users add, edit, or delete notes to enhance user experience.
