### ISSUE TITLE
Notes feature

### ISSUE THREAD

**Issue by uditjainstjis** [rizkytegar/veonote#66]
Website don't have anything in it , i added dynamic notes feature to map and place notes which is responsive too!!,
give this issue a hacktoberfest tag and assign this to me, i will work on adding editing and deleting feature to note.
<img width="390" alt="image" src="https://github.com/user-attachments/assets/0feaf232-0cd5-45b0-948e-64ac0cd44f5d">
<img width="965" alt="image" src="https://github.com/user-attachments/assets/04f062ba-f82c-4a2d-8f2b-9fdc0532a0eb">

**Comment by uditjainstjis** [comment]
Thanks, but in my hactober pulls it is saying not accepted, can you add one more tag , hacktober-accepted to it? so i can work further , thanks!

**Comment by rizkytegar** [comment]
Thanks for your pull request @uditjainstjis, I'm very busy at the moment. so no time to work on open source including hacktoberfest.
